--------------------------------------------------------
--  File created - Monday-August-21-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TS_KOTA
--------------------------------------------------------

  CREATE TABLE "TRAM"."TS_KOTA" 
   (	"ID" NUMBER(*,0), 
	"NAMA" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TS_KELURAHAN
--------------------------------------------------------

  CREATE TABLE "TRAM"."TS_KELURAHAN" 
   (	"ID" NUMBER(*,0), 
	"KECAMATAN_ID" NUMBER(*,0), 
	"NAMA" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TS_STATUS_PERNIKAHAN
--------------------------------------------------------

  CREATE TABLE "TRAM"."TS_STATUS_PERNIKAHAN" 
   (	"ID" NUMBER(*,0), 
	"NAMA" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TS_AGAMA
--------------------------------------------------------

  CREATE TABLE "TRAM"."TS_AGAMA" 
   (	"ID" NUMBER(*,0), 
	"NAMA" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TS_KECAMATAN
--------------------------------------------------------

  CREATE TABLE "TRAM"."TS_KECAMATAN" 
   (	"ID" NUMBER(*,0), 
	"KOTA_ID" NUMBER(*,0), 
	"NAMA" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KARYAWAN_MASTER
--------------------------------------------------------

  CREATE TABLE "TRAM"."KARYAWAN_MASTER" 
   (	"ID" NUMBER(*,0), 
	"NAMA_DEPAN" VARCHAR2(50 BYTE), 
	"NAMA_TENGAH" VARCHAR2(50 BYTE), 
	"NAMA_BELAKANG" VARCHAR2(50 BYTE), 
	"TEMPAT_LAHIR" VARCHAR2(255 BYTE), 
	"TANGGAL_LAHIR" DATE, 
	"NO_ID" VARCHAR2(30 BYTE), 
	"ALAMAT" VARCHAR2(255 BYTE), 
	"KOTA_ID" NUMBER(*,0), 
	"KECAMATAN_ID" NUMBER(*,0), 
	"KELURAHAN_ID" NUMBER(*,0), 
	"RT" NUMBER(*,0), 
	"RW" NUMBER(*,0), 
	"JENIS_KELAMIN_ID" NUMBER(*,0), 
	"STATUS_PERNIKAHAN_ID" NUMBER(*,0), 
	"NPWP" VARCHAR2(30 BYTE), 
	"BPJS" VARCHAR2(30 BYTE), 
	"AGAMA_ID" NUMBER(*,0), 
	"NIK" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TS_JENIS_KELAMIN
--------------------------------------------------------

  CREATE TABLE "TRAM"."TS_JENIS_KELAMIN" 
   (	"ID" NUMBER(*,0), 
	"NAMA" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TS_KOTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAM"."TS_KOTA_PK" ON "TRAM"."TS_KOTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TS_KOTA_INDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAM"."TS_KOTA_INDEX" ON "TRAM"."TS_KOTA" ("NAMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TS_KELURAHAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAM"."TS_KELURAHAN_PK" ON "TRAM"."TS_KELURAHAN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TS_KELURAHAN_INDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAM"."TS_KELURAHAN_INDEX" ON "TRAM"."TS_KELURAHAN" ("NAMA", "KECAMATAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TS_STATUS_PERNIKAHAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAM"."TS_STATUS_PERNIKAHAN_PK" ON "TRAM"."TS_STATUS_PERNIKAHAN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TS_STATUS_PERNIKAHAN_INDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAM"."TS_STATUS_PERNIKAHAN_INDEX" ON "TRAM"."TS_STATUS_PERNIKAHAN" ("NAMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TS_AGAMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAM"."TS_AGAMA_PK" ON "TRAM"."TS_AGAMA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TS_AGAMA_INDEX
--------------------------------------------------------

  CREATE INDEX "TRAM"."TS_AGAMA_INDEX" ON "TRAM"."TS_AGAMA" ("NAMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TS_KECAMATAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAM"."TS_KECAMATAN_PK" ON "TRAM"."TS_KECAMATAN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TS_KECAMATAN_INDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAM"."TS_KECAMATAN_INDEX" ON "TRAM"."TS_KECAMATAN" ("NAMA", "KOTA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KARYAWAN_MASTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAM"."KARYAWAN_MASTER_PK" ON "TRAM"."KARYAWAN_MASTER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TS_JENIS_KELAMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAM"."TS_JENIS_KELAMIN_PK" ON "TRAM"."TS_JENIS_KELAMIN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TS_JENIS_KELAMIN_INDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "TRAM"."TS_JENIS_KELAMIN_INDEX" ON "TRAM"."TS_JENIS_KELAMIN" ("NAMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TS_KOTA
--------------------------------------------------------

  ALTER TABLE "TRAM"."TS_KOTA" ADD CONSTRAINT "TS_KOTA_UK" UNIQUE ("NAMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TRAM"."TS_KOTA" ADD CONSTRAINT "KOTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TRAM"."TS_KOTA" MODIFY ("NAMA" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."TS_KOTA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TS_KELURAHAN
--------------------------------------------------------

  ALTER TABLE "TRAM"."TS_KELURAHAN" ADD CONSTRAINT "TS_KELURAHAN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TRAM"."TS_KELURAHAN" MODIFY ("NAMA" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."TS_KELURAHAN" MODIFY ("KECAMATAN_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."TS_KELURAHAN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TS_STATUS_PERNIKAHAN
--------------------------------------------------------

  ALTER TABLE "TRAM"."TS_STATUS_PERNIKAHAN" ADD CONSTRAINT "STATUS_NIKAH_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TRAM"."TS_STATUS_PERNIKAHAN" MODIFY ("NAMA" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."TS_STATUS_PERNIKAHAN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TS_AGAMA
--------------------------------------------------------

  ALTER TABLE "TRAM"."TS_AGAMA" ADD CONSTRAINT "TS_AGAMA_UK" UNIQUE ("NAMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TRAM"."TS_AGAMA" ADD CONSTRAINT "AGAMA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TRAM"."TS_AGAMA" MODIFY ("NAMA" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."TS_AGAMA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TS_KECAMATAN
--------------------------------------------------------

  ALTER TABLE "TRAM"."TS_KECAMATAN" ADD CONSTRAINT "TS_KECAMATAN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TRAM"."TS_KECAMATAN" MODIFY ("NAMA" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."TS_KECAMATAN" MODIFY ("KOTA_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."TS_KECAMATAN" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KARYAWAN_MASTER
--------------------------------------------------------

  ALTER TABLE "TRAM"."KARYAWAN_MASTER" ADD CONSTRAINT "KARYAWAN_MASTER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TRAM"."KARYAWAN_MASTER" MODIFY ("NIK" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."KARYAWAN_MASTER" MODIFY ("AGAMA_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."KARYAWAN_MASTER" MODIFY ("BPJS" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."KARYAWAN_MASTER" MODIFY ("NPWP" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."KARYAWAN_MASTER" MODIFY ("STATUS_PERNIKAHAN_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."KARYAWAN_MASTER" MODIFY ("JENIS_KELAMIN_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."KARYAWAN_MASTER" MODIFY ("KELURAHAN_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."KARYAWAN_MASTER" MODIFY ("KECAMATAN_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."KARYAWAN_MASTER" MODIFY ("KOTA_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."KARYAWAN_MASTER" MODIFY ("ALAMAT" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."KARYAWAN_MASTER" MODIFY ("NO_ID" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."KARYAWAN_MASTER" MODIFY ("TANGGAL_LAHIR" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."KARYAWAN_MASTER" MODIFY ("TEMPAT_LAHIR" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."KARYAWAN_MASTER" MODIFY ("NAMA_DEPAN" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."KARYAWAN_MASTER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TS_JENIS_KELAMIN
--------------------------------------------------------

  ALTER TABLE "TRAM"."TS_JENIS_KELAMIN" ADD CONSTRAINT "TS_JENIS_KELAMIN_UK" UNIQUE ("NAMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TRAM"."TS_JENIS_KELAMIN" ADD CONSTRAINT "JENIS_KELAMIN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TRAM"."TS_JENIS_KELAMIN" MODIFY ("NAMA" NOT NULL ENABLE);
  ALTER TABLE "TRAM"."TS_JENIS_KELAMIN" MODIFY ("ID" NOT NULL ENABLE);
